---
title: ''
output: html_document 
params:
  projID: LaGrange New 1200-Foot Lock
  p2ID: 505374
  p2sub: ""

---
```{css, echo=FALSE}


th {    vertical-align: top;    
    padding: 5px;
    
}
td {    vertical-align: top;
  padding: 5px;
}

html {
    display: table;
    margin: 5px;
}


body{ /* Normal  */
      font-size: 12px;
  }



.table > tbody {
  padding: 1.5px;
}

@media print {
body{ /* Normal  */
      font-size: 14px;
  }

body {-webkit-print-color-adjust: exact;}

  .item-box {
    page-break-inside: avoid;
  }
  .section-box {
    page-break-inside: avoid;
  }

  .page-break {
  page-break-after: always;
  }

}
```

```{r data crunch, warning=FALSE, include=FALSE}
library(readr) 
library(magrittr) 
library(dplyr) 
library(kableExtra) 
library(tidyverse)
library(formattable)
options(scipen = 999)
erisk_item <- read.csv("../data/RISKLIST_FULL_0320245.csv")
risk_item_db<-data.frame(erisk_item)
erisk_project <- read_csv("../data/PROJECTLIST_FULL_03226024.csv", show_col_types = FALSE)
risk_project_db<-data.frame(erisk_project)

risk_item_db<-risk_item_db |>
  left_join(risk_project_db|>
              select(PROJECT_ID, PRIMARYMISSION))

RiskDeets <- risk_item_db |>
  select("PROJECT_ID","RISK_IDENTIFIER","P2_SUB_IDENTIFIER", "PROJECT_NAME","P2_NUMBER","RISK_NAME",
         "RISKCATEGORY","RISK_STATEMENT" ,"LIFECYCLEPHASENAME","MILESTONE",
         "LIKELIHOOD","DISCIPLINE", "PERFORMANCEIMPACT", "PERFORMANCE_RANK_DESC",
         "COST_IMPACT_MOSTLIKELY", "COST_RANK_DESC", "SCHEDULE_IMPACT_MOSTLIKELY",
         "SCHEDULE_RANK_DESC", "PRIMARYMISSION", "USACE_ORGANIZATION")
```

```{r echo=FALSE, eval = params$projID != ""}
Risk_List_Proj <-filter(RiskDeets, RiskDeets$PROJECT_NAME == params$projID)
Risk_List_Proj$COST_IMPACT_MOSTLIKELY <- as.character(
  formattable::currency(Risk_List_Proj$COST_IMPACT_MOSTLIKELY))
```

```{r echo=FALSE, eval = params$p2ID != ""}
Risk_List_Proj <-filter(RiskDeets, RiskDeets$P2_NUMBER == params$p2ID)
Risk_List_Proj$COST_IMPACT_MOSTLIKELY <- as.character(
  formattable::currency(Risk_List_Proj$COST_IMPACT_MOSTLIKELY))
```

```{r echo=FALSE, eval = params$p2sub != ""}
Risk_List_Proj <-filter(Risk_List_Proj, Risk_List_Proj$P2_SUB_IDENTIFIER == params$p2sub)
Risk_List_Proj$COST_IMPACT_MOSTLIKELY <- as.character(
  formattable::currency(Risk_List_Proj$COST_IMPACT_MOSTLIKELY))
```


```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
RiskDeetsTable<-Risk_List_Proj |>
  select("RISK_IDENTIFIER","RISK_NAME","RISKCATEGORY","RISK_STATEMENT" ,"LIFECYCLEPHASENAME","MILESTONE","LIKELIHOOD","DISCIPLINE", "PERFORMANCEIMPACT",
         "COST_IMPACT_MOSTLIKELY", "SCHEDULE_IMPACT_MOSTLIKELY")|>
    rename("RISK" = RISK_IDENTIFIER,
         "RISK NAME" = RISK_NAME,
         "RISK CATEGORY" = RISKCATEGORY,
         "RISK STATEMENT" = RISK_STATEMENT,
         "PHASE" = LIFECYCLEPHASENAME,
         "PERFORMANCE IMPACT TYPE" = PERFORMANCEIMPACT,
         "COST IMPACT" = COST_IMPACT_MOSTLIKELY,
         "SCHEDULE IMPACT (DAYS)" = SCHEDULE_IMPACT_MOSTLIKELY)

```

```{r, echo=FALSE, warning=FALSE, message=FALSE,results='asis'}

header<-paste("Project:",params$projID)
header2<-if (params$p2sub != ""){
  paste("SubID:", params$p2sub)}

cat("###",header,header2)

```


#### `r unique(Risk_List_Proj$PRIMARYMISSION)`

##### `r unique(Risk_List_Proj$USACE_ORGANIZATION)`

#### All Project Risks
<center>
```{r,  echo = FALSE, warning=FALSE, results='asis'}
RiskDeetsTable<-RiskDeetsTable |>
kableExtra::kbl("html",align = 'ccclcccccc') |>
    kable_styling(bootstrap_options = c( "condensed"),
                  full_width = F)|>
   column_spec(4, width_min = '3in')
RiskDeetsTable<-kableExtra::landscape(RiskDeetsTable)
RiskDeetsTable
```
</center>