---
title: ""
runtime: shiny
output: html_document
params:
  projID: ""
  p2ID: 479265
  p2sub: ""
---

```{css formatting, echo=FALSE}
 h2,h3, h5,h7 {
  text-align: center;
}
h4 {
font-weight: 300;
text-align: center;
}


@media print {
body {-webkit-print-color-adjust: exact;}

  .item-box {
    page-break-inside: avoid;
  }
  .section-box {
    page-break-inside: avoid;
  }

  .page-break {
  page-break-after: always;
  }

}
```

```{r load in data, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(readr)
library(dplyr) 
library(kableExtra) 
library(formattable)
library(dplyr)
library(utils)
library(erarr)
options(scipen = 999)

erisk_item <- readr::read_csv("../data/erisk_item.csv")
risk_item_db<-data.frame(erisk_item)
erisk_project <- readr::read_csv("../data/erisk_project.csv")
risk_project_db<-data.frame(erisk_project)
erisk_archive <- readr::read_csv("../data/erisk_modeled.csv",
                          show_col_types=FALSE)


erisk_mean <- erisk_archive|>
  dplyr::select(COST_MEAN, SCHEDULE_MEAN,OUTCOME_MEAN,PROJECT_ID,RISK_ID)

risk_item_db<-risk_item_db |>
  dplyr::left_join(risk_project_db|>
              dplyr::select(PROJECT_ID, PRIMARYMISSION))|>
    left_join(erisk_mean, by = join_by(PROJECT_ID,RISK_ID))




RiskDeets <- risk_item_db |>
  dplyr::select("PROJECT_ID","P2_NUMBER","P2_SUB_IDENTIFIER","RISK_IDENTIFIER", "PROJECT_NAME","RISK_NAME","RISKCATEGORY","RISK_STATEMENT" ,"LIFECYCLEPHASENAME","MILESTONE","LIKELIHOOD","DISCIPLINE","PROB_OCCURRENCE", "PERFORMANCEIMPACT","PERFORMANCEIMPACT_IMPCT", "PERFORMANCE_RANK_DESC", "PERFORMANCEIMPACT_RISK_RANKING","COST_IMPACT_LOWEST","COST_MEAN","COST_IMPACT_HIGHEST", "COST_RANK_DESC","COST_RISK_RANKING","SCHEDULE_IMPACT_LOWEST","SCHEDULE_MEAN","SCHEDULE_IMPACT_HIGHEST", "SCHEDULE_RANK_DESC", "SCHEDULE_RISK_RANKING", "PRIMARYMISSION", "USACE_ORGANIZATION")

```

```{r filter projs, echo=FALSE, eval = params$projID != "" | params$p2ID != "" | params$p2sub != ""}
# Initialize Risk_List_Proj as the complete dataset
Risk_List_Proj <- RiskDeets

# Apply filters based on available parameters
if (params$projID != "") {
  proj_risks <- dplyr::filter(Risk_List_Proj, PROJECT_NAME == params$projID)
  header <- paste("Project:", Risk_List_Proj$PROJECT_NAME[1])
}

if (params$p2ID != "") {
  proj_risks<- dplyr::filter(Risk_List_Proj, P2_NUMBER == params$p2ID)
  header <- paste("P2 Number:", Risk_List_Proj$P2_NUMBER[1])
}

if (params$p2sub != "") {
  proj_risks<- dplyr::filter(Risk_List_Proj, P2_SUB_IDENTIFIER == params$p2sub)
  header <- paste("SubID:", params$p2sub)
}

# Conditional header2 assignment
header2 <- if (params$p2sub != "") {
  paste("SubID:", params$p2sub)
} else {
  ""
}

proj_risk_item<- dplyr::slice_head(Risk_List_Proj)
```

###### Report Created On: `r format(Sys.time(), '%d %B, %Y')`
```{r, echo=FALSE, warning=FALSE, message=FALSE,results='asis'}

cat("###",header,header2)

```

##### `r proj_risk_item$PRIMARYMISSION` (Current Phase:`r proj_risk_item$LIFECYCLEPHASENAME`)
##### `r proj_risk_item$USACE_ORGANIZATION`
### Project Risk Summary 
<center>
```{r proj risk pies, message=FALSE, warning=FALSE, echo=FALSE,fig.height=2, fig.width=7}
#make pie plots 
  cost_pie<- erarr::pieprep(proj_risks, "COST_RANK_DESC")
  schedule_pie<-erarr::pieprep(proj_risks, "SCHEDULE_RANK_DESC")
  perform_pie<- erarr::pieprep(proj_risks, "PERFORMANCE_RANK_DESC")

  erarr::pie_plots(cost_pie,schedule_pie,perform_pie)


```
</center>
#### Top 4 Cost Impacts (All Phases)
``` {r cost risk log, echo = FALSE, warning=FALSE}
cost_top4s<-proj_risks |>
  mutate(MAX_COST = pmax(COST_IMPACT_LOWEST, COST_MEAN, COST_IMPACT_HIGHEST))|>
  arrange(desc(COST_RISK_RANKING), desc(MAX_COST), desc(PROB_OCCURRENCE))|>
      dplyr::select(RISK_IDENTIFIER, RISK_NAME, RISKCATEGORY , MILESTONE , LIKELIHOOD, MAX_COST) |>
    dplyr::slice_head(n=4)|>
  mutate(MAX_COST = as.character(formattable::currency(MAX_COST)))|>
  kableExtra::kbl(format = "html", escape = F, col.names =c("Risk ID","Risk Name","Risk Category","Project Milestone","Likelihood", "Cost Impact"), align="clcccc", row.names = FALSE)|>
  kableExtra::kable_styling(bootstrap_options = c( "hover", "condensed", "responsive"))

cost_top4s
```

#### Top 4 Schedule Impacts (All Phases)
``` {r schedule risk log, echo = FALSE, warning=FALSE}
schedule_top4s<-proj_risks |>
   mutate(MAX_SCHED = pmax(SCHEDULE_IMPACT_LOWEST, SCHEDULE_MEAN, SCHEDULE_IMPACT_HIGHEST))|>
  arrange(desc(SCHEDULE_RISK_RANKING), desc(MAX_SCHED), desc(PROB_OCCURRENCE))|>
      dplyr::select(RISK_IDENTIFIER, RISK_NAME, RISKCATEGORY , MILESTONE , LIKELIHOOD, MAX_SCHED) |>
    dplyr::slice_head(n=4)|>
  kableExtra::kbl(format = "html", escape = F, col.names =c("Risk ID","Risk Name","Risk Category","Project Milestone","Likelihood", "Schedule Impact (Days)"), align="clcccc", row.names = FALSE)|>
  kableExtra::kable_styling(bootstrap_options = c( "hover", "condensed", "responsive"))
schedule_top4s
```



#### Top 4 Performance Impacts (All Phases)
``` {r perform risk log, echo = FALSE, warning=FALSE}
perform_log_table<-proj_risks |>
  arrange(desc(PERFORMANCEIMPACT_RISK_RANKING), desc(PERFORMANCEIMPACT_IMPCT), desc(PROB_OCCURRENCE))|>
  dplyr::select(RISK_IDENTIFIER, RISK_NAME, RISKCATEGORY , MILESTONE , LIKELIHOOD, PERFORMANCE_RANK_DESC) |>
  dplyr::slice_head(n=4)|>
  kableExtra::kbl(format = "html", escape = F, col.names =c("Risk ID","Risk Name","Risk Category","Project Milestone","Likelihood", "Performance Impact"), align="clcccc", row.names = FALSE)|>
  kableExtra::kable_styling(bootstrap_options = c( "hover", "condensed", "responsive"))
perform_log_table
```
