---
output:
  html_document: default
  pdf_document: default
---

```{r pull data from api, include=FALSE}
library(httr) # handles GET requests through the API
library(jsonlite) # Converts JSON input to df and readable output
library(writexl) 

# add useful functions
make_URL <- function(children) {
  return(paste("https://err.sec.usace.army.mil", children, sep=""))
}

make_headers <- function(token, userSpec) {
  return(httr::add_headers(c('Accept'="application/json, text/plain, */*", 'Authorization'=paste('Bearer', token), 'Access-Control-Allow-Methods'='GET'), 'user'=userSpec))
}

#api/vocabulary

  header <- make_headers(token, userSpec)
  accURL <- make_URL("/api/vocabulary")
  data = httr::GET(accURL, header)
  apiVocab = jsonlite::fromJSON(rawToChar(data$content))

  
  header <- make_headers(token, userSpec)
  accURL <- make_URL("/api/help")
  data = httr::GET(accURL, header)
  apihelp = jsonlite::fromJSON(rawToChar(data$content))
  writexl::write_xlsx(data.frame(apihelp$rows), "excelOutput\\New Files\\apiHelp.xlsx")
  
  apihelp$rows
  
    helpID <- "rr_1"
  header <- make_headers(token, userSpec)
  accURL <- make_URL(paste("/api/help/", helpID, sep=""))
  helpID = httr::GET(accURL, header)
  helpID = jsonlite::fromJSON(rawToChar(helpID$content))
  #writexl::write_xlsx(data.frame(apihelp$rows), "excelOutput\\New Files\\apiHelp.xlsx")
  
  helpID$rows
  # not much useful info here

#/api/userinfo/{name}
  name <- 'benac.ryan.j.1613988200'
  header <- make_headers(token, userSpec)
  accURL <- make_URL(paste("/api/userinfo/", name, sep=""))
  userinfo = httr::GET(accURL, header)
  
#/api/projects
  apiSpec <- "/api/projects"
  header <- make_headers(token, userSpec)
  accURL <- make_URL(apiSpec)
  projects = httr::GET(accURL, header)
  projects = jsonlite::fromJSON(rawToChar(projects$content))
  writexl::write_xlsx(data.frame(projects$rows), "excelOutput\\New Files\\projects.xlsx")

  projects$rows

#/api/projects/{id}
   projectID <- 115
  apiSpec <- paste("/api/projects/", projectID, sep="")
  header <- make_headers(token, userSpec)
  accURL <- make_URL(apiSpec)
  projectID = httr::GET(accURL, header)
  projectID = jsonlite::fromJSON(rawToChar(projectID$content))
  writexl::write_xlsx(data.frame(projectID$rows), "excelOutput\\New Files\\projectID115.xlsx")

  projectID$rows

#/api/projects/{id}/projectphases
  projectID <- 115
  apiSpec <- paste("/api/projects/", projectID, "/projectphases", sep="")
  header <- make_headers(token, userSpec)
  accURL <- make_URL(apiSpec)
  projectphases = httr::GET(accURL, header)
  projectphases = jsonlite::fromJSON(rawToChar(projectphases$content))
  writexl::write_xlsx(data.frame(projectphases$rows), "excelOutput\\New Files\\projectID115_projectphases.xlsx")

  projectphases$rows

#/api/projects/{id}/users
   projectID <- 115
  apiSpec <- paste("/api/projects/", projectID, "/users", sep="")
  header <- make_headers(token, userSpec)
  accURL <- make_URL(apiSpec)
  users = httr::GET(accURL, header)
  users = jsonlite::fromJSON(rawToChar(users$content))
  writexl::write_xlsx(data.frame(users$rows), "excelOutput\\New Files\\projectID115_users.xlsx")

  users$rows
  
#/api/projects/{id}/risks
    projectID <- 3576
  apiSpec <- paste("/api/projects/", projectID, "/risks", sep="")
  header <- make_headers(token, userSpec)
  accURL <- make_URL(apiSpec)
  risks = httr::GET(accURL, header)
  risks = jsonlite::fromJSON(rawToChar(risks$content))
  writexl::write_xlsx(data.frame(risks$rows), "excelOutput\\New Files\\projectID3576_risks.xlsx")

  risks$rows

  
#/api/projects/{id}/risks/{riskid}/treatments

  projectID <- 3576
  riskID = 1

  apiSpec <- paste("/api/projects/", projectID, "/risks/", riskID, "/treatments",sep="")
  header <- make_headers(token, userSpec)
  accURL <- make_URL(apiSpec)
  treatments = httr::GET(accURL, header)
  treatments = jsonlite::fromJSON(rawToChar(treatments$content))
  writexl::write_xlsx(data.frame(treatments$rows), "excelOutput\\New Files\\project3576_riskTreatmentsHeaders.xlsx")

  treatments$metaData 

#/api/projects/{id}/risks/{riskid}/transactions
projectID <- 3576
  riskID = 1

  apiSpec <- paste("/api/projects/", projectID, "/risks/", riskID, "/transactions",sep="")
  header <- make_headers(token, userSpec)
  accURL <- make_URL(apiSpec)
  riskTransactions = httr::GET(accURL, header)
  riskTransactions = jsonlite::fromJSON(rawToChar(riskTransactions$content))
  writexl::write_xlsx(data.frame(riskTransactions$rows), "excelOutput\\New Files\\project3576_riskTransactions.xlsx")

  riskTransactions$rows  

```

```{r data crunch, include=FALSE}
library(readr) 
library(magrittr) 
library(dplyr) 
library(kableExtra) 
library(rlang)
library(plotly)
library(dplyr)
library(crosstalk)
library(tidyverse)
library(leaflet)
library(DT)
erisk_item <- read_csv("data/RiskItem_FullView_Update.csv")
risk_item_db<-data.frame(erisk_item)
erisk_project <- read_csv("data/RiskProject_FullView.csv")
risk_project_db<-data.frame(erisk_project)


#cast numeric to string
risk_item_db$RISK_ID<-as.character(risk_item_db$RISK_ID)
risk_item_db$riskIDCode<-paste(risk_item_db$RISK_ID,"-",risk_item_db$DISCIPLINE_ACRONYM)

erisk_ItemProj<-left_join(risk_item_db, risk_project_db, by = "PROJECT_ID")
erisk_testing<-erisk_ItemProj[,c(3,5,6,8,22,27,32,40,51,56,64,65)]

erisk_testing$PROJECT_NAME.x<-as.factor(erisk_testing$PROJECT_NAME.x)
erisk_testing$USACE_ORGANIZATION<-as.factor(erisk_testing$USACE_ORGANIZATION)

erisk_testing<-erisk_testing %>%
  rename("Project Name" = PROJECT_NAME.x,
         "Risk" = RISK_NAME,
         "Risk Category" = RISKCATEGORY,
         "Risk Statement" = RISK_STATEMENT,
         "USACE Organization" = USACE_ORGANIZATION)


erisk_testing<-erisk_testing %>% 
  dplyr::mutate("Cost Risk" = case_when(COST_RISK_RANKING == 0 ~ "",
                                      COST_RISK_RANKING == 1 ~ "Opportunity",
                                      COST_RISK_RANKING == 2 ~ "Low",
                                      COST_RISK_RANKING == 3 ~ "Moderate",
                                      COST_RISK_RANKING == 4 ~ "High")) %>%
                mutate("Performance Risk" = case_when(PERFORMANCEIMPACT_RISK_RANKING == 0 ~ "",
                                                      PERFORMANCEIMPACT_RISK_RANKING == 1 ~ "Opportunity",
                                                      PERFORMANCEIMPACT_RISK_RANKING == 2 ~ "Low",
                                                      PERFORMANCEIMPACT_RISK_RANKING == 3 ~ "Moderate",
                                                      PERFORMANCEIMPACT_RISK_RANKING == 4 ~ "High"))%>%
                mutate("Schedule Risk" = case_when(SCHEDULE_RISK_RANKING == 0 ~ "",
                                                   SCHEDULE_RISK_RANKING == 1 ~ "Opportunity",
                                                   SCHEDULE_RISK_RANKING == 2 ~ "Low",
                                                   SCHEDULE_RISK_RANKING == 3 ~ "Moderate",
                                                   SCHEDULE_RISK_RANKING == 4 ~ "High"))

  

```

```{r leaflet map, echo = FALSE, warning=FALSE}
erisk_testing1<-erisk_testing %>%
  select('Project Name', 'Risk', 'Risk Category', 'Risk Statement', 'Cost Risk', 'Performance Risk','Schedule Risk',riskIDCode, PROJECT_LATITUDE, PROJECT_LONGITUDE, 'USACE Organization')


cost_Sample<-erisk_testing1 %>%
  filter(`Cost Risk`!="") %>% 
  group_by(`Project Name`) %>%
  count(`Cost Risk`)%>%
  group_by(`Project Name`) %>%
  mutate(perc = round(n/sum(n)*100,2)) %>%
   mutate('color' = case_when(`Cost Risk` == "Opportunity" ~ 'deepskyblue', 
  `Cost Risk`=='Low'~'green', 
  `Cost Risk` =='Moderate'~'orange',
  `Cost Risk` == 'High'~ 'red')) %>%
  plotly::arrange(factor(`Cost Risk`,levels=c('Opportunity', 'Low', 'Moderate', 'High')))
 


shared_proj<-SharedData$new(erisk_testing1, group = "projfilt")


cost_risk_plot<-erisk_testing1 %>%
  filter(`Cost Risk`!="") %>% 
  group_by(`Project Name`) %>%
  count(`Cost Risk`)%>%
  group_by(`Project Name`) %>%
  mutate(perc = round(n/sum(n)*100,2)) %>%
   mutate('color' = case_when(`Cost Risk` == "Opportunity" ~ 'deepskyblue', 
  `Cost Risk`=='Low'~'green', 
  `Cost Risk` =='Moderate'~'orange',
  `Cost Risk` == 'High'~ 'red')) %>%
  plotly::arrange(factor(`Cost Risk`,levels=c('Opportunity', 'Low', 'Moderate', 'High')))%>%
  SharedData$new(group = "projfilt", key = ~`Project Name`)

schedule_risk_plot<-erisk_testing1 %>%
  filter(`Schedule Risk`!="") %>%
  group_by(`Project Name`) %>%
  count(`Schedule Risk`)%>%
  group_by(`Project Name`) %>%
  mutate(perc = round(n/sum(n)*100,2))%>%
  plotly::arrange(factor(`Schedule Risk`,levels=c('Opportunity', 'Low', 'Moderate', 'High')))%>%
   mutate('color' = case_when(`Schedule Risk` == "Opportunity" ~ 'deepskyblue', 
  `Schedule Risk`=='Low'~'green', 
  `Schedule Risk` =='Moderate'~'orange',
  `Schedule Risk` == 'High'~ 'red')) %>%
  SharedData$new(group = "projfilt")


perform_risk_plot<-erisk_testing1 %>%
  filter(`Performance Risk`!="") %>%
  group_by(`Project Name`) %>%
  count(`Performance Risk`)%>%
  group_by(`Project Name`) %>%
  mutate(perc = round(n/sum(n)*100,2))%>%
  plotly::arrange(factor(`Performance Risk`,levels=c('Opportunity', 'Low', 'Moderate', 'High')))%>%
   mutate('color' = case_when(`Performance Risk` == "Opportunity" ~ 'deepskyblue', 
  `Performance Risk`=='Low'~'green', 
  `Performance Risk` =='Moderate'~'orange',
  `Performance Risk` == 'High'~ 'red')) %>%
  SharedData$new(group = "projfilt")

filter_select(
  id = "prj",
  label = "Project",
  sharedData = shared_proj,
  group = ~`Project Name`
)

# filter_select(
#   id = "dst",
#   label = "District",
#   sharedData = shared_proj,
#   group = ~`USACE Organization`
# )




shared_proj %>%
  leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addCircleMarkers(lng=~PROJECT_LONGITUDE, lat=~PROJECT_LATITUDE,color="aqua", fillColor="aqua", weight=2)



cost_plot<- cost_risk_plot %>%
  plot_ly(type = "pie", values = ~n, labels = ~`Cost Risk`, sort=FALSE, marker = list(colors = ~color))%>%
  layout(title = "Cost Risk",  showlegend = F,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
cost_plot

# schedule_plot<-schedule_risk_plot%>% 
#   plot_ly(labels = ~`Schedule Risk`, values = ~n, sort=FALSE, marker = list(colors = ~color)) %>%
#   add_pie() %>%
#   layout(title = "Schedule Risk",  showlegend = F,
#                       xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
#                       yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
# 
# performance_plot<-perform_risk_plot %>%
#   plot_ly(labels = ~`Performance Risk`, values = ~n, sort=FALSE, marker = list(colors = ~color)) %>%
#   add_pie() %>%
#   layout(title = "Performance Risk",  showlegend = F,
#                       xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
#                       yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
# 

# plotty<-bscols(widths = c(4,4,4), cost_plot, schedule_plot, performance_plot)

# plotty

shared_proj %>%
  DT::datatable(filter = "top",
                extensions = 'Buttons', 
                options = list(buttons = c('copy','csv','excel','pdf'),
                          lengthMenu=list(c(10,30, 50, -1), c('10', '30', '50', 'All')),
                          paging = T)) %>%
     formatStyle('Performance Risk', backgroundColor = styleEqual(
                     c("", 'Opportunity', 'Low', 'Moderate', 'High'),
                     c('white', 'deepskyblue', 'green', 'orange', 'red')
                   )) %>%
                   formatStyle('Cost Risk', backgroundColor = styleEqual(
                    c("", 'Opportunity', 'Low', 'Moderate', 'High'),
                     c('white', 'deepskyblue', 'green', 'orange', 'red')
                   )) %>%
                   formatStyle('Schedule Risk', backgroundColor = styleEqual(
                     c("", 'Opportunity', 'Low', 'Moderate', 'High'),
                    c('white', 'deepskyblue', 'green', 'orange', 'red')
                   ))
```
