---
title: ""
output: html_document
params:
  riskID: Environmental Surveys - Wetlands
  projID: St. Augustine Back Bay CSRM
  p2ID: 479265
---

```{css, echo=FALSE}
h1, h2, h3, h4, h5, h6, h7, h9 {
  text-align: center;
}
```

```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(readr) 
library(magrittr) 
library(dplyr) 
library(kableExtra) 
library(rlang)
library(plotly)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(tidyverse)
library(english)
library(DT)
options(scipen = 999)

erisk_item <- read.csv("C:/workspace/e-rarr/RiskItemReportShinyApp/data/RISKLISTFULL.csv")
risk_item_db<-data.frame(erisk_item)
erisk_project <- read_csv("C:/workspace/e-rarr/RiskItemReportShinyApp/data/PROJECTLIST_FULL.csv")
risk_project_db<-data.frame(erisk_project)

risk_item_db<-left_join(risk_item_db, risk_project_db , by = "PROJECT_ID")|>
  select(-ends_with(".y")) 

RiskDeets <- risk_item_db |>
  select("PROJECT_ID","P2_NUMBER.x","RISK_IDENTIFIER", "PROJECT_NAME.x","RISK_NAME","RISKCATEGORY","RISK_STATEMENT" ,"LIFECYCLEPHASENAME.x","MILESTONE","LIKELIHOOD","DISCIPLINE", "PERFORMANCEIMPACT", "PERFORMANCE_RANK_DESC", "PERFORMANCEIMPACT_RISK_RANKING","COST_IMPACT_MOSTLIKELY", "COST_RANK_DESC","COST_RISK_RANKING", "SCHEDULE_IMPACT_MOSTLIKELY", "SCHEDULE_RANK_DESC", "SCHEDULE_RISK_RANKING", "PRIMARYMISSION", "USACE_ORGANIZATION.x")


Risk_List_Proj <-filter(RiskDeets, RiskDeets$PROJECT_NAME.x == params$projID | RiskDeets$P2_NUMBER.x == params$p2ID)
Risk_List_Proj$COST_IMPACT_MOSTLIKELY <- as.character(formattable::currency(Risk_List_Proj$COST_IMPACT_MOSTLIKELY))



proj_risks<-filter(Risk_List_Proj, Risk_List_Proj$PROJECT_NAME == params$projID | Risk_List_Proj$P2_NUMBER.x == params$p2ID)
proj_risk_item<- slice_head(Risk_List_Proj)

proj_risks <- proj_risks %>%
  mutate(
    'costcolor' = case_when(
      COST_RANK_DESC == "No Risk" ~ "#FFFFFF",
      COST_RANK_DESC == "Opportunity" ~ 'rgb(31,120,180)',
      COST_RANK_DESC == 'Low' ~ 'rgb(51,160,44)',
      COST_RANK_DESC == 'Medium' ~ 'rgb(255,127,0)',
      COST_RANK_DESC == 'High' ~ 'rgb(227,26,28)'
    )
  ) |>
  mutate(
    'schedulecolor' = case_when(
      SCHEDULE_RANK_DESC == "No Risk" ~ "#FFFFFF",
      SCHEDULE_RANK_DESC == "Opportunity" ~ 'rgb(31,120,180)',
      SCHEDULE_RANK_DESC == 'Low' ~ 'rgb(51,160,44)',
      SCHEDULE_RANK_DESC == 'Medium' ~ 'rgb(255,127,0)',
      SCHEDULE_RANK_DESC == 'High' ~ 'rgb(227,26,28)'
    )
  ) |>
  mutate(
    'performancecolor' = case_when(
      PERFORMANCE_RANK_DESC == "No Risk" ~ '#FFFFFF',
      PERFORMANCE_RANK_DESC == "Opportunity" ~ 'rgb(31,120,180)',
      PERFORMANCE_RANK_DESC == 'Low' ~
        'rgb(51,160,44)',
      PERFORMANCE_RANK_DESC == 'Medium' ~ 'rgb(255,127,0)',
      PERFORMANCE_RANK_DESC == 'High' ~ 'rgb(227,26,28)'
    )
  )

         

```




## Project: `r proj_risk_item$PROJECT_NAME.x`
##### `r proj_risk_item$PRIMARYMISSION` `r proj_risk_item$LIFECYCLEPHASENAME.x`
##### `r proj_risk_item$USACE_ORGANIZATION.x`

### All Project Risk Impacts

```{r proj risk pies, message=FALSE, warning=FALSE, echo=FALSE, fig.align='center',fig.height=3, fig.width=7}
##where cost impact =yes 
riskdf<-proj_risks
   cost_pie<- riskdf |>
    group_by(COST_RANK_DESC) |>
    summarize(count = n())|>
    filter(COST_RANK_DESC != "No Risk") |>
    mutate('color' = case_when(COST_RANK_DESC == "Opportunity" ~'rgb(31,120,180)', 
  COST_RANK_DESC=='Low'~'rgb(51,160,44)', 
  COST_RANK_DESC =='Medium'~ 'rgb(255,127,0)',
  COST_RANK_DESC == 'High'~ 'rgb(227,26,28)' ))|>
  plotly::arrange(factor(COST_RANK_DESC,levels=c('Opportunity', 'Low', 'Medium', 'High')))
  
 schedule_pie<- riskdf |>
    group_by(SCHEDULE_RANK_DESC) |>
    summarize(count = n())|>
    filter(SCHEDULE_RANK_DESC != "No Risk")|>
    mutate('color' = case_when(SCHEDULE_RANK_DESC == "Opportunity" ~ 'rgb(31,120,180)', 
  SCHEDULE_RANK_DESC=='Low'~'rgb(51,160,44)', 
  SCHEDULE_RANK_DESC =='Medium'~ 'rgb(255,127,0)',
  SCHEDULE_RANK_DESC == 'High'~ 'rgb(227,26,28)' ))|>
  plotly::arrange(factor(SCHEDULE_RANK_DESC,levels=c('Opportunity', 'Low', 'Medium', 'High')))
 
  perform_pie<- riskdf |>
    group_by(PERFORMANCE_RANK_DESC) |>
    summarize(count = n())|>
    filter(PERFORMANCE_RANK_DESC != "No Risk")|>
     mutate('color' = case_when(PERFORMANCE_RANK_DESC == "Opportunity" ~ 'rgb(31,120,180)', 
  PERFORMANCE_RANK_DESC=='Low'~'rgb(51,160,44)', 
  PERFORMANCE_RANK_DESC =='Medium'~ 'rgb(255,127,0)',
  PERFORMANCE_RANK_DESC == 'High'~ 'rgb(227,26,28)' ))|>
  plotly::arrange(factor(PERFORMANCE_RANK_DESC,levels=c('Opportunity', 'Low', 'Medium', 'High')))

  
  
  fig <- plot_ly(textfont = list(color = '#FFFFFF')) |>
    add_pie(
      data = cost_pie,
      values =  ~ count,
      labels = ~ COST_RANK_DESC,
      sort = FALSE,
      title="Cost",
      textinfo = 'value',
      textfont = list(color = '#FFFFFF'),
      domain = list(row = 0, column = 0),
      marker = list(
        colors = ~ color,
        line = list(color = '#FFFFFF', width = 1.5)
      )
    ) |>
    add_pie(
      data = schedule_pie,
      values = ~ count,
      labels = ~ SCHEDULE_RANK_DESC,
      textinfo = 'value',
      textfont = list(color = '#FFFFFF'),
      sort = FALSE,
      title = "Schedule",
      domain = list(row = 0, column = 1),
      marker = list(
        colors = ~ color,
        line = list(color = '#FFFFFF', width = 1.5)
      )
    ) |>
    add_pie(
      data = perform_pie,
      values = ~ count,
      labels = ~ PERFORMANCE_RANK_DESC,
      textinfo = 'value',
      title = "Performance",
      textfont = list(color = '#FFFFFF'),
      sort = FALSE,
      domain = list(row = 0, column = 2),
      marker = list(
        colors = ~ color,
        line = list(color = '#FFFFFF', width = 1.5)
      )
    )
  
  pies<-fig |>
    layout(title = "", showlegend = T,
                      grid=list(rows=1, columns=3),legend= list(orientation = 'h'))
  pies

```

``` {r proj risk log, echo = FALSE, warning=FALSE}


risk_log_table<-proj_risks |>
  select(RISK_IDENTIFIER, RISK_NAME, COST_RISK_RANKING, SCHEDULE_RISK_RANKING, PERFORMANCEIMPACT_RISK_RANKING, costcolor, schedulecolor, performancecolor )


risk_log_table|>
  mutate(
    COST_RISK_RANKING = cell_spec(COST_RISK_RANKING, "html", color = costcolor, align = 'c', background = costcolor),
    SCHEDULE_RISK_RANKING = cell_spec(SCHEDULE_RISK_RANKING, "html", color = schedulecolor, align = 'c', background = schedulecolor),
    PERFORMANCEIMPACT_RISK_RANKING = cell_spec(PERFORMANCEIMPACT_RISK_RANKING, "html", color = performancecolor, align = 'c', background = performancecolor) ) |>
  select(RISK_IDENTIFIER, RISK_NAME,COST_RISK_RANKING, SCHEDULE_RISK_RANKING, PERFORMANCEIMPACT_RISK_RANKING) |>
  separate(RISK_IDENTIFIER,c("code", "rnkorder"), sep="-", remove = FALSE) |>
  dplyr::arrange(code,as.numeric(rnkorder))|>
  select(RISK_IDENTIFIER, RISK_NAME,COST_RISK_RANKING, SCHEDULE_RISK_RANKING, PERFORMANCEIMPACT_RISK_RANKING) |>
  kbl(format = "html", escape = F, col.names =c("Risk ID","Risk","Cost","Schedule","Performance"), align="ccccc", row.names = FALSE)|>
  kable_styling(bootstrap_options = c( "hover", "condensed", "responsive"))

                                                    
```
