---
output: html_document
runtime: shiny
---

```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(readr) 
library(magrittr) 
library(dplyr) 
library(kableExtra) 
library(rlang)
library(plotly)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(crosstalk)
library(tidyverse)
library(leaflet)
library(DT)
library(shinythemes)
library(shiny)
library(bslib)
library(stringr)

erisk_item <- read_csv("C:/workspace/e-rarr/RiskItemReportShinyApp/data/RiskItem_FullView_Update.csv")
risk_item_db<-data.frame(erisk_item)
erisk_project <- read_csv("C:/workspace/e-rarr/RiskItemReportShinyApp/data/RiskProject_FullView.csv")
risk_project_db<-data.frame(erisk_project)
risk_treat <- read_csv("C:/workspace/e-rarr/RiskItemReportShinyApp/data/RiskTreatment_FullView.csv")
imagepath<-"C:/workspace/e-rarr/RiskItemReportShinyApp/images/castle.tif"



erisk_ItemProj<-left_join(risk_item_db, risk_project_db, by = "PROJECT_ID")


RiskImpactTable<-erisk_ItemProj[,c("PROJECT_NAME.x", "RISK_NAME", "USACE_ORGANIZATION","P2_LOOKUP")]
```


```{r , echo=FALSE }
shinyApp(
  ui = fluidPage(theme = bslib::bs_theme(
    bootswatch = "cosmo"),
    navbarPage(title="Risk Analysis Reporting System",
  tabPanel("National"),
  tabPanel("Division"),
  tabPanel("District"),
  tabPanel("Project",
    sidebarLayout(
      sidebarPanel(selectInput("projectInput", "Select a project", choices=c(" ",RiskImpactTable$PROJECT_NAME.x)),
selectInput("riskInput", "Select a risk item", choices=c(" ",RiskImpactTable$RISK_NAME)
),
    actionButton("render", "View Report"),
    downloadButton("report", "Download report"),),
    
  mainPanel(
    tabsetPanel(id="Report Tabs",
      tabPanel("Risk Item Report",
      htmlOutput("reportrend")),
  tabPanel("Project Report"),
  tabPanel("All Risk Items",
           htmlOutput("AllRiskRend")),
  )))))),
  server = function(input, output, session) {
    observe({
      risks = RiskImpactTable |>
        filter(RiskImpactTable$PROJECT_NAME.x == input$projectInput) |>
        pull(RISK_NAME) |>
        unique() |>
        sort()
       updateSelectInput(
        inputId = "riskInput", 
        choices = risks
       )
    })
    # observe({
    #   risks = RiskImpactTable |>
    #     filter(RiskImpactTable$P2_LOOKUP == input$p2Input) |>
    #   pull(RISK_NAME) |>
    #     unique() |>
    #     sort()
    #    updateSelectInput(
    #     inputId = "riskInput",
    #     choices = risks
    #     )
    # })
      observeEvent(input$render, {
      output$reportrend <- renderUI({
        includeHTML(
          rmarkdown::render("RiskItemReport.Rmd", params=list(projID = input$projectInput, riskID= input$riskInput)
          )
        )
      })
    })
            observeEvent(input$render, {
      output$AllRiskRend <- renderUI({
        includeHTML(
          rmarkdown::render("AllRiskDetailTable.Rmd", params=list(projID = input$projectInput)
          )
        )
      })
    })
    output$report <- downloadHandler(
      # For PDF output, change this to "report.pdf"
      filename = function(){
        paste0(input$projectInput," - ",input$riskInput,"RiskItemReport",".html")
      },
      content = function(file) {
        # Copy the report file to a temporary directory before processing it, in
        # case we don't have write permissions to the current working dir (which
        # can happen when deployed).
        tempReport <- file.path(tempdir(), "RiskItemReport.Rmd")
        file.copy("RiskItemReport.Rmd", tempReport, overwrite = TRUE)

        # Set up parameters to pass to Rmd document
        params <- list( projID = input$projectInput, riskID= input$riskInput)

        # Knit the document, passing in the `params` list, and eval it in a
        # child of the global environment (this isolates the code in the document
        # from the code in this app).
        rmarkdown::render(tempReport, output_file = file,
          params = params,
          envir = new.env(parent = globalenv()))
      })
  },
  options=list(height=2000, width=1000)
)
```