```{r data crunch,include=FALSE}
library(readr) 
library(magrittr) 
library(dplyr) 
library(kableExtra) 
library(rlang)
library(plotly)
library(dplyr)
library(crosstalk)
library(tidyverse)
library(leaflet)
setwd('C:/workspace/erarr/old_xxx')
erisk_item <- read_csv("C:/workspace/erarr/old_xxx/data/RiskItem_FullView.csv")
erisk_item <- read_csv("./data/RiskItem_FullView.csv")
risk_item_db<-data.frame(erisk_item)
erisk_project <- read_csv("data/RiskProject_FullView.csv")
risk_project_db<-data.frame(erisk_project)


#cast numeric to string
#risk_item_db$riskIDCode<-paste(risk_item_db$RISK_ID+"-"+risk_item_db$DISCIPLINE_ACRONYM)

erisk_ItemProj<-left_join(risk_item_db, risk_project_db, by = "PROJECT_ID")
erisk_testing<-erisk_ItemProj[,c(3,5,6,8,22,27,32,40,55,63,64)]


```

```{r leaflet map, echo=FALSE}
shared_proj<-SharedData$new(erisk_testing)

filter_select(
  id = "dst",
  label = "District",
  sharedData = shared_proj,
  group = ~USACE_ORGANIZATION
)

filter_select(
  id = "prj",
  label = "Project",
  sharedData = shared_proj,
  group = ~PROJECT_NAME.x
)



shared_proj %>%
  DT::datatable(filter = "top",
                extensions= c("Buttons"),
        options(buttons = list(
        I("colvis"),  # turn columns on and off
        "csv",  # download as .csv
        "excel"  # download as .xlsx
        )
        )
  )

shared_proj %>%
  leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addCircleMarkers(lng=~PROJECT_LONGITUDE, lat=~PROJECT_LATITUDE,color="aqua", fillColor="aqua", weight=2)


shared_proj %>%
  group_by(COST_RISK) %>% 
  summarize(count = n()) %>% 
  plot_ly(labels = ~COST_RISK, values = ~count, text = ~count) %>% 
  add_pie(hole = 0.6) %>% 
  layout(title = "Donut charts using Plotly",  showlegend = T,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         colorway = c('green','orange','red'))

  

```

```{r data table, include=FALSE}
library(DT) 
risk$PROGRAM<-as.factor(risk$PROGRAM)
risk$PROJECT<-as.factor(risk$PROJECT)
risk$SCHEDULE_RISK<-as.factor(risk$SCHEDULE_RISK)
risk$EFFICACY_RISK<-as.factor(risk$EFFICACY_RISK)
risk$COST_RISK<-as.factor(risk$COST_RISK)

erisk_df <- risk %>% select(OBJECTID,PROGRAM, PROJECT,risk_no_link, CONCERNS, RISKCATEGORY, RISK_STRATEGY, EFFICACY_RISK, COST_RISK, SCHEDULE_RISK)
```

This data table can be filtered

```{r show table, echo=FALSE}
DT::datatable(erisk_df[,2:10], rownames=FALSE, filter='top',options=list(orderMulti = TRUE)) %>%
  formatStyle('SCHEDULE_RISK', backgroundColor = styleEqual(c('Low','Moderate','High'), c('green','orange','red'))) %>%
  formatStyle('EFFICACY_RISK', backgroundColor = styleEqual(c('Low','Moderate','High'), c('green','orange','red'))) %>%
  formatStyle('COST_RISK', backgroundColor = styleEqual(c('Low','Moderate','High'), c('green','orange','red')))


```

```{r show bagel, echo=FALSE}
bagel_plot<- erisk_df %>%
  group_by(COST_RISK) %>% 
  summarize(count = n())%>% 
  plot_ly(labels = ~COST_RISK, values = ~count, text = ~count) %>% 
  add_pie(hole = 0.6) %>% 
  layout(title = "Donut charts using Plotly",  showlegend = T,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         colorway = c('green','orange','red'))



values<- erisk_df %>%
  group_by(COST_RISK) %>%
  summarize(count=n())


high<- values %>% filter(COST_RISK =="High")

bagel_plot <- layout(bagel_plot, annotations=list(text=paste(round((high$count / sum(values$count) * 100),2), "%", sep=""), "showarrow"=F))
bagel_plot


```

Crosstalk Example

```{r crosstalkin, echo=FALSE}

shared_risk<- SharedData$new(erisk_df, key = ~OBJECTID, group = "Program")

program_filter<- filter_select(
  id = "prgm",
  label = "PROGRAM",
  sharedData = shared_risk,
  group = ~PROGRAM
)

projects_filter <- filter_select(
  id = "prj",
  label = "PROJECT",
  sharedData = shared_risk,
  group = ~PROJECT
)

test <- shared_risk %>% 
  DT::datatable(erisk_df[2:10], rownames=FALSE) %>%
  formatStyle('SCHEDULE_RISK', backgroundColor = styleEqual(c('Low','Moderate','High'), c('green','orange','red'))) %>%
  formatStyle('EFFICACY_RISK', backgroundColor = styleEqual(c('Low','Moderate','High'), c('green','orange','red'))) %>%
  formatStyle('COST_RISK', backgroundColor = styleEqual(c('Low','Moderate','High'), c('green','orange','red')))




COST_RISK<- erisk_df %>%
  group_by(COST_RISK) %>% 
  summarize(count = n()) %>% 
  plot_ly(labels = ~COST_RISK, values = ~count, text = ~count) %>% 
  add_pie(hole = 0.6) %>% 
  layout(title = "Cost Risk",  showlegend = T,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

values<- erisk_df %>%
  group_by(COST_RISK) %>%
  summarize(count=n())


```
